export const GET_SHOES_REQUEST = "getShoes/request";
export const GET_SHOES_SUCCESS = "getShoes/success";
export const GET_SHOES_FAILURE = "getShoes/failure";


//for add to cart
export const ADD_PRODUCT_CART_REQUEST = 'ADD_PRODUCT_CART_REQUEST';
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
export const ADD_PRODUCT_CART_FAILURE = 'ADD_PRODUCT_CART_FAILURE';

//for deleting cart prod
export const REMOVE_PRODUCT_CART_REQUEST = 'REMOVE_PRODUCT_CART_REQUEST';
export const REMOVE_PRODUCT_CART_SUCCESS = 'REMOVE_PRODUCT_CART_SUCCESS';
export const REMOVE_PRODUCT_CART_FAILURE = 'REMOVE_PRODUCT_CART_FAILURE';

//for cart-counter
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

