

export const GET_SHOP_BY_CATEGORY_REQUEST = "GET_SHOP_BY_CATEGORY_REQUEST"
export const GET_SHOP_BY_CATEGORY_SUCCESS = "GET_SHOP_BY_CATEGORY_SUCCESS"
export const GET_SHOP_BY_CATEGORY_FAILURE = "GET_SHOP_BY_CATEGORY_FAILURE"
